### ISSUE TITLE
Email server not running?

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/chef-buildingdb#10]
I've noticed that anything that handles email isn't working at the moment, perhaps because the SMTP server isn't running (I can't ping the SMTP server defined in the dev-server config) or the authentication details have changed?

The email config is set here: https://github.com/polygon-city/chef-buildingdb/blob/master/templates/default/config.js.erb#L18

I can't remember how this was set up in the end – is this something I have access to restart? Otherwise, can someone take a look at the SMTP server and give it a kick if it's down?

**Comment by robhawkes** [comment]
I'm seeing `Email report from or to address not found in configuration` in the logs which implies that the email server credentials aren't actually being set properly by Chef when it generates the `config.js` file. I don't know were the email credentials are actually set using Chef so I can't check if they are actually missing or not.

**Comment by baldur** [comment]
@robhawkes sorry I am late to the party ... this still a problem?

**Comment by robhawkes** [comment]
A bit of work has been done on better handling email issues, though in this case I think we're ok as I'm receiving emails fine when I register a new account on Polygon City.
