### ISSUE TITLE
Increase upload size limit, add error message when limit hit

### ISSUE THREAD

**Issue by meetar** [polygon-city/chef-buildingdb#3]
Attempted to upload `esb.zip`, 5.7MB – the "Upload" button changed to "Uploading…" but nothing else happened on the page.

Console error: `Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)`

Attempting to upload anything else, even after logging out and back in, now results in an error on the page: "Access denied", with no console errors.

Todo:
- Handle 413 errors
- Increase upload limit
- Show error message when the limit is hit

**Comment by baldur** [comment]
@meetar have you verified this locally, outside of the aws instance? The webserver in front of the node application has an upload limit of 50MB. The node app might also have a limit set and the error could be coming from there. Handling the error and showing the message would also be a responsibility of the application code.

**Comment by baldur** [comment]
yikes just realized this issue is old ... closing. Handling of the error should be handled in the app
