### ISSUE TITLE
Add 2dsphere spatial index in Mongo for location field

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/chef-buildingdb#4]
It looks like the 2dsphere spatial index on the location field isn't being set in the Mongo database correctly: http://54.174.22.198/search/near/51.5073219,-0.1276474,1000

I'm unsure exactly how the indexes are set using this Chef instance but to do it manually I use the following:

```
db.buildings.ensureIndex( { location: "2dsphere" } );
```

**Comment by bcamper** [comment]
@baldur, do you know where this does/doesn't happen currently?

**Comment by baldur** [comment]
it is supposed to happen here https://github.com/polygon-city/chef-buildingdb/blob/master/recipes/app.rb#L38 here is the file that gets run

https://github.com/polygon-city/chef-buildingdb/blob/master/templates/default/setup.js.erb

I can do some digging to make sure

**Comment by baldur** [comment]
It appears to be there?
db.buildings.getIndexes()
[
    {
        "v" : 1,
        "key" : {
            "_id" : 1
        },
        "ns" : "building-database.buildings",
        "name" : "_id_"
    },
    {
        "v" : 1,
        "key" : {
            "slug.id" : 1
        },
        "unique" : true,
        "ns" : "building-database.buildings",
        "name" : "slug.id_1"
    },
    {
        "v" : 1,
        "key" : {
            "location" : "2dsphere"
        },
        "ns" : "building-database.buildings",
        "name" : "location_2dsphere"
    }
]

**Comment by baldur** [comment]
could this be a version differences we are on 2.4.9

**Comment by robhawkes** [comment]
Hmm, odd! Looks like the right index is there so I wonder why it's not happy when it tries to do a spatial query (using the link in the first post). I'm using 2.6.5 locally but [`2dsphere` arrived in 2.4](http://docs.mongodb.org/manual/core/2dsphere/) so it should be ok. There are a couple of 2.6-only things but we're not using them so that shouldn't cause a problem. Saying that, I've done a little poking around it looks like [there's a bug in 2.4](https://jira.mongodb.org/browse/SERVER-4572) that prevents `2dsphere` from working correctly.

Is it possible for us to use 2.6, or some version with that bug fixed (after 2.5.5)?

**Comment by baldur** [comment]
@robhawkes I'll update the version. I assume we don't care about the data collected thus far.

**Comment by robhawkes** [comment]
Awesome, thank you – hopefully that fixes it. I've no attachment to the existing data, though I didn't upload any of it. I'd say we're ok if it vanishes, we can always re-upload it again.

**Comment by baldur** [comment]
try it now here: http://polygon-city-dev-us-east-ext-1847103710.us-east-1.elb.amazonaws.com/

**Comment by baldur** [comment]
I am at 2.6.8 now but unable to signup a user http://polygon-city-dev-us-east-ext-1847103710.us-east-1.elb.amazonaws.com

not seeing anything meaningful in the log and the same is happening on the vagrant version

**Comment by robhawkes** [comment]
This is potentially related to an change in error handling I made for the signup flow earlier – I'll look into why the message is blank.

As for the cause, have working SMTP settings [been added to the config](https://github.com/polygon-city/building-database/blob/master/config/config.sample.js#L12)? I wasn't able to sign up with the previous version either, though I hadn't created an issue for it.

**Comment by baldur** [comment]
fixed ... can you check it now ... ignore the domain the email is sent from ... until the real one is hooked up

**Comment by robhawkes** [comment]
It works great, thanks!
