### ISSUE TITLE
Build error due to ./bin/deploy dev timeout

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/chef-buildingdb#7]
I'm seeing errors in the CircleCI build due to hitting the 300s timeout while running `./bin/deploy dev`. Any ideas? The app and tests run ok locally (and the tests are passing in Circle).

```
./bin/deploy dev
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/..
Installing builder 3.2.2
Installing multi_json 1.11.0
Installing jmespath 1.0.2
Installing multi_xml 0.5.5
Installing aws-sdk-core 2.0.30
Installing aws-sdk-resources 2.0.30
Installing aws-sdk 2.0.30
Installing json 1.8.2
Installing mini_portile 0.6.2
Installing nokogiri 1.6.5
Installing aws-sdk-v1 1.59.0
Using bundler 1.7.13
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.


./bin/deploy dev returned exit code 1

Deploying: | status: failed timeout: 300 -- time passed: 302.829597946Action failed: ./bin/deploy dev
```

**Comment by bcamper** [comment]
@baldur possible this is this just a timeout config issue somewhere?

**Comment by baldur** [comment]
missing grunt ... which appears to have been moved to devDependencies again

**Comment by robhawkes** [comment]
Hmm, I moved a few things to `devDependencies` without thinking – I forgot we use Grunt as the launcher to do processing. I'll move it back and see if any of the other packages need moving too.

**Comment by robhawkes** [comment]
Ok that fixed it – I basically moved everything out of `devDependencies` for now as we need mostly all of it for the tests and other things and I forgot the CircleCI setup is running under a production environment variable.
