### ISSUE TITLE
Build failure on CircleCI

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/chef-buildingdb#8]
For the past couple of weeks I've noticed that CircleCI is failing to build and deploy as updates are pushed to Polygon City – [take this build for example](https://circleci.com/gh/polygon-city/building-database/84). This is happening for every build.

The Polygon City tests pass (well, sometimes they fail but that's a separate issue) and there are no obvious error messages so I'm unsure what's wrong and what I need to fix. The only vaguely useful message is the following, which appears after what looks like a timeout in the build:

```
./bin/deploy dev returned exit code 1
```

@baldur: Could you take a look and let me know if there's anything more obvious you can find about what's going on?

**Comment by baldur** [comment]
just had to shake the wires ... fixed now

**Comment by robhawkes** [comment]
Awesome, it's working great now. Thanks!
